name = "anifoxwatch-api"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

# Use serverless-http/express adapter behavior
[observability]
enabled = true
